language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
# command to run tests
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: 
  coverage run test_rpn.py
after_success:
  - coveralls
