language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
# command to run tests
install:
  - pip install python-coveralls
script: 
  coverage --source=rpn.py test_rpn.py
after_success:
  - coveralls
