language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
# command to run tests
env:
  matrix:
    - $COVPYYAML=cov3-default,coveralls3
    - $COVPYYAML=cov4-pyyaml,coveralls4
    - $COVPYYAML=cov41-pyyaml,coveralls41
    - $COVPYYAML=cov3-default,coveralls3
    - $COVPYYAML=cov4-pyyaml,coveralls4
    - $COVPYYAML=cov41-pyyaml,coveralls41
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: 
  coverage python test_rpn.py
after_success:
  - coveralls
